openapi: 3.0.0
info:
  title: User Registration API
  version: "1.0.0"
  description: API para el registro de usuarios y asignación de roles por defecto.
servers:
  - url: http://localhost:3000/api/users
    description: Servidor local

paths:
  /register:
    post:
      summary: Registrar un nuevo usuario
      tags:
        - Usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - email
                - password
                - phone
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                password:
                  type: string
                phone:
                  type: string
      responses:
        "201":
          description: Usuario registrado con éxito
        "400":
          description: Faltan campos obligatorios
        "409":
          description: El correo ya está registrado
        "500":
          description: Error interno del servidor
